apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metabase-pvc
  namespace: plot-listing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust storage size as needed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase-deployment
  namespace: plot-listing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
      - name: metabase
        image: metabase/metabase:latest
        ports:
        - containerPort: 3000
        env:
        - name: MB_DB_TYPE
          value: "postgres"
        - name: MB_DB_HOST
          value: "db"
        - name: MB_DB_PORT
          value: "5432"
        - name: MB_DB_DBNAME
          value: "listingdb"
        - name: MB_DB_USER
          value: "user"
        - name: MB_DB_PASS
          value: "password"
        volumeMounts:
        - name: metabase-storage
          mountPath: /metabase-data
      volumes:
      - name: metabase-storage
        persistentVolumeClaim:
          claimName: metabase-pvc